export const mockTableData = {
  "status": 200,
  "body": {
    "receiveStocks": [
      {
        "id": 1,
        "customerId": 1,
        "hubId": 1,
        "orderDetailId": 1,
        "trackingNo": "track_123",
        "status": "wait",
        "expectedArrivedOn": "2024/06/29",
        "receivedOn": null,
        "publicRemarks": "public_remarks_***",
        "publicRemarksFilePath": null,
        "privateRemarks": null,
        "privateRemarksFilePath": null,
        "isTransacted": false,
        "createdAt": "2024/06/25 13:37:29",
        "createdCustomerBy": 1,
        "createdEmployeeBy": null,
        "updatedAt": "2024/06/25 13:37:29",
        "deletedAt": null,
        "createdOn": "2024/06/25",
        "updatedOn": "2024/06/25",
        "uuid": "6aa012bc-eabb-41de-8f67-d52404d781d3",
        "code": "YP1-W1",
        "statusLabel": "入荷待ち",
        "receiveStockDetails": [
          {
            "id": 1,
            "receiveStockId": 1,
            "productId": 2,
            "requestedReceiveQuantity": 40,
            "inspectedQuantity": 0,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "uuid": "f0dfec9c-aee1-4db3-909a-98a2e78ddf1d",
            "receiveQuantity": 0,
            "product": {
              "id": 2,
              "customerId": 1,
              "hubId": 1,
              "name": "テスト商品C",
              "nameToSlip": null,
              "productType": "normal",
              "sku": "YP1SKU2",
              "fnsku": null,
              "janCode": "jan789",
              "asin": null,
              "label": "jan789",
              "productLabelType": "jan_code",
              "productUrl": null,
              "productApiUrl": null,
              "productImageUrl": "https://link.storjshare.io/s/jwvbvjlf2gbhug5l5ndj573eploq/iiuu/p2.jpeg?wrap=0",
              "weight": 0,
              "height": 0,
              "width": 0,
              "depth": 0,
              "unitPrice": 900,
              "isDisabled": false,
              "createdAt": "2024/06/25 13:37:29",
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null
            },
            "receiveStock": {
              "id": 1,
              "customerId": 1,
              "hubId": 1,
              "orderDetailId": 1,
              "trackingNo": "track_123",
              "status": "wait",
              "expectedArrivedOn": "2024-06-29",
              "receivedOn": null,
              "publicRemarks": "public_remarks_***",
              "publicRemarksFilePath": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "isTransacted": false,
              "createdAt": "2024/06/25 13:37:29",
              "createdCustomerBy": 1,
              "createdEmployeeBy": null,
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null,
              "code": "YP1-W1"
            }
          },
          {
            "id": 2,
            "receiveStockId": 1,
            "productId": 3,
            "requestedReceiveQuantity": 59,
            "inspectedQuantity": 0,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "uuid": "3458d878-63a8-4dcc-b198-a6803dd8762b",
            "receiveQuantity": 0,
            "product": {
              "id": 3,
              "customerId": 1,
              "hubId": 1,
              "name": "テスト商品D",
              "nameToSlip": null,
              "productType": "normal",
              "sku": "YP1SKU3",
              "fnsku": null,
              "janCode": "janABC",
              "asin": null,
              "label": "YP1-3",
              "productLabelType": "product_id",
              "productUrl": null,
              "productApiUrl": null,
              "productImageUrl": "https://link.storjshare.io/s/juxm7vvey6nkdmd2hi3fkj2seura/iiuu/p3.jpeg?wrap=0",
              "weight": 0,
              "height": 0,
              "width": 0,
              "depth": 0,
              "unitPrice": 1100,
              "isDisabled": false,
              "createdAt": "2024/06/25 13:37:29",
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null
            },
            "receiveStock": {
              "id": 1,
              "customerId": 1,
              "hubId": 1,
              "orderDetailId": 1,
              "trackingNo": "track_123",
              "status": "wait",
              "expectedArrivedOn": "2024-06-29",
              "receivedOn": null,
              "publicRemarks": "public_remarks_***",
              "publicRemarksFilePath": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "isTransacted": false,
              "createdAt": "2024/06/25 13:37:29",
              "createdCustomerBy": 1,
              "createdEmployeeBy": null,
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null,
              "code": "YP1-W1"
            }
          }
        ],
        "orderDetail": {
          "id": 1,
          "orderId": 1,
          "productId": 5,
          "mallProductId": null,
          "trackingNo": null,
          "productName": "初期カート商品A",
          "variation": "白",
          "quantity": 100,
          "orderStatus": "un_processed",
          "directDebitStatus": "un_direct_debit",
          "mall": "alibaba",
          "mallOrderId": null,
          "shopName": "ショップ名A",
          "unitPrice": 230,
          "postage": 0,
          "publicRemarks": null,
          "publicRemarksFilePath": null,
          "privateRemarks": null,
          "privateRemarksFilePath": null,
          "receipt": null,
          "receiptFilePath": null,
          "integratedId": null,
          "createdAt": "2024/06/25 13:37:29",
          "createdCustomerBy": 1,
          "createdEmployeeBy": null,
          "updatedAt": "2024/06/25 13:37:29",
          "deletedAt": null,
          "createdOn": "2024/06/25",
          "updatedOn": "2024/06/25",
          "uuid": "28826251-d3ac-4b02-bbf5-34d473f59881",
          "order": {
            "id": 1,
            "customerId": 1,
            "hubId": 1,
            "orderType": "oem",
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "customer": {
              "id": 1,
              "name": "KOU EI",
              "nameKana": null,
              "companyName": null,
              "email": "yiwu+customer@test.com",
              "emailVerifiedAt": "2024-06-25T04:37:29.000000Z",
              "emailVerifyLimitedAt": null,
              "emailVerifiedToken": null,
              "currentHubId": null,
              "amazonApiCode": null,
              "chatWorkId": null,
              "dedicatedAccountId": null,
              "countryId": null,
              "postalCode": null,
              "prefectureName": null,
              "cityName": null,
              "townName": null,
              "buildingName": null,
              "tel": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "createdAt": "2024-06-25T04:37:29.000000Z",
              "updatedAt": "2024-06-25T04:37:29.000000Z",
              "deletedAt": null,
              "createdOn": "2024/06/25",
              "updatedOn": "2024/06/25",
              "code": "YP1",
              "plans": [
                {
                  "id": 1,
                  "hubId": 1,
                  "name": "義鳥 無料プラン",
                  "imagePath": null,
                  "planHeaderText": null,
                  "paymentMethodCode": null,
                  "trialPeriodLength": null,
                  "trialPeriodUnit": null,
                  "trialPrice": null,
                  "paymentPeriodLength": null,
                  "paymentPeriodUnit": null,
                  "paymentPrice": null,
                  "description1": null,
                  "description2": null,
                  "description3": null,
                  "description4": null,
                  "description5": null,
                  "description6": null,
                  "description7": null,
                  "description8": null,
                  "description9": null,
                  "description10": null,
                  "purchaseFee": null,
                  "couponPeriodLength": null,
                  "couponPeriodUnit": null,
                  "couponEnableCount": null,
                  "couponPercent": null,
                  "applyButtonText": null,
                  "applyButtonColorCode": null,
                  "isDisabled": false,
                  "isFree": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null,
                  "pivot": {
                    "customer_id": 1,
                    "plan_id": 1,
                    "status": "using"
                  },
                  "hub": {
                    "id": 1,
                    "name": "義鳥",
                    "iconPath": null,
                    "code": "yiwu",
                    "countryId": 1,
                    "currencyId": 1,
                    "forContact": false,
                    "isDomestic": 1,
                    "companyName": null,
                    "postalCode": null,
                    "prefectureName": null,
                    "cityName": null,
                    "townName": null,
                    "buildingName": null,
                    "invoiceNo": null,
                    "description": null,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null
                  }
                }
              ],
              "currentCustomerPlan": null,
              "customerPlans": [
                {
                  "id": 1,
                  "customerId": 1,
                  "planId": 1,
                  "groupId": null,
                  "status": "using",
                  "isFree": "0",
                  "employeeId": 1,
                  "chatWorkId": null,
                  "lastPaidAt": null,
                  "createdAt": null,
                  "updatedAt": null,
                  "deletedAt": null,
                  "statusLabel": "利用中",
                  "hub": {
                    "id": 1,
                    "name": "義鳥",
                    "iconPath": null,
                    "code": "yiwu",
                    "countryId": 1,
                    "currencyId": 1,
                    "forContact": false,
                    "isDomestic": 1,
                    "companyName": null,
                    "postalCode": null,
                    "prefectureName": null,
                    "cityName": null,
                    "townName": null,
                    "buildingName": null,
                    "invoiceNo": null,
                    "description": null,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null
                  },
                  "plan": {
                    "id": 1,
                    "hubId": 1,
                    "name": "義鳥 無料プラン",
                    "imagePath": null,
                    "planHeaderText": null,
                    "paymentMethodCode": null,
                    "trialPeriodLength": null,
                    "trialPeriodUnit": null,
                    "trialPrice": null,
                    "paymentPeriodLength": null,
                    "paymentPeriodUnit": null,
                    "paymentPrice": null,
                    "description1": null,
                    "description2": null,
                    "description3": null,
                    "description4": null,
                    "description5": null,
                    "description6": null,
                    "description7": null,
                    "description8": null,
                    "description9": null,
                    "description10": null,
                    "purchaseFee": null,
                    "couponPeriodLength": null,
                    "couponPeriodUnit": null,
                    "couponEnableCount": null,
                    "couponPercent": null,
                    "applyButtonText": null,
                    "applyButtonColorCode": null,
                    "isDisabled": false,
                    "isFree": 1,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null,
                    "hub": {
                      "id": 1,
                      "name": "義鳥",
                      "iconPath": null,
                      "code": "yiwu",
                      "countryId": 1,
                      "currencyId": 1,
                      "forContact": false,
                      "isDomestic": 1,
                      "companyName": null,
                      "postalCode": null,
                      "prefectureName": null,
                      "cityName": null,
                      "townName": null,
                      "buildingName": null,
                      "invoiceNo": null,
                      "description": null,
                      "createdAt": "2024/06/25 13:37:28",
                      "updatedAt": "2024/06/25 13:37:28",
                      "deletedAt": null
                    }
                  }
                }
              ]
            },
            "code": "YP1-O1",
            "postageTotal": 0,
            "otherPriceTotal": 0,
            "total": 280000,
            "detailCount": 3,
            "hub": {
              "id": 1,
              "name": "義鳥",
              "iconPath": null,
              "code": "yiwu",
              "countryId": 1,
              "currencyId": 1,
              "forContact": false,
              "isDomestic": 1,
              "companyName": null,
              "postalCode": null,
              "prefectureName": null,
              "cityName": null,
              "townName": null,
              "buildingName": null,
              "invoiceNo": null,
              "description": null,
              "createdAt": "2024/06/25 13:37:28",
              "updatedAt": "2024/06/25 13:37:28",
              "deletedAt": null,
              "createdOn": "2024/06/25",
              "updatedOn": "2024/06/25",
              "groups": [
                {
                  "id": 1,
                  "name": "A班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 2,
                  "name": "B班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 3,
                  "name": "C班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 4,
                  "name": "D班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 5,
                  "name": "E班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                }
              ],
              "country": {
                "id": 1,
                "code": "86",
                "name": "中国",
                "isJapan": false,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              },
              "currency": {
                "id": 1,
                "name": "CNY",
                "nameToJp": "元",
                "decimalPlaces": 2,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              },
              "currentTaxRate": {
                "id": 1,
                "hubId": 1,
                "name": "消費税",
                "startedOn": "2024-06-26",
                "rate": 0,
                "createdAt": "2024/06/26 11:33:21",
                "updatedAt": "2024/06/26 11:33:21"
              },
              "currentCustomerPlan": {
                "id": 1,
                "hubId": 1,
                "name": "義鳥 無料プラン",
                "imagePath": null,
                "planHeaderText": null,
                "paymentMethodCode": null,
                "trialPeriodLength": null,
                "trialPeriodUnit": null,
                "trialPrice": null,
                "paymentPeriodLength": null,
                "paymentPeriodUnit": null,
                "paymentPrice": null,
                "description1": null,
                "description2": null,
                "description3": null,
                "description4": null,
                "description5": null,
                "description6": null,
                "description7": null,
                "description8": null,
                "description9": null,
                "description10": null,
                "purchaseFee": null,
                "couponPeriodLength": null,
                "couponPeriodUnit": null,
                "couponEnableCount": null,
                "couponPercent": null,
                "applyButtonText": null,
                "applyButtonColorCode": null,
                "isDisabled": false,
                "isFree": 1,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null,
                "customerPlans": [
                  {
                    "id": 1,
                    "customerId": 1,
                    "planId": 1,
                    "groupId": null,
                    "status": "using",
                    "isFree": "0",
                    "employeeId": 1,
                    "chatWorkId": null,
                    "lastPaidAt": null,
                    "createdAt": null,
                    "updatedAt": null,
                    "deletedAt": null
                  }
                ]
              }
            },
            "orderDetails": [
              {
                "id": 1,
                "orderId": 1,
                "productId": 5,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品A",
                "variation": "白",
                "quantity": 100,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": "alibaba",
                "mallOrderId": null,
                "shopName": "ショップ名A",
                "unitPrice": 230,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              },
              {
                "id": 2,
                "orderId": 1,
                "productId": 1,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品B",
                "variation": "黒",
                "quantity": 20,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": "alibaba",
                "mallOrderId": null,
                "shopName": "ショップ名A",
                "unitPrice": 350,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              },
              {
                "id": 3,
                "orderId": 1,
                "productId": 6,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品C",
                "variation": "赤",
                "quantity": 500,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": null,
                "mallOrderId": null,
                "shopName": "ショップ名B",
                "unitPrice": 500,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              }
            ]
          },
          "orderStatusLabel": "未処理",
          "product": {
            "id": 5,
            "customerId": 1,
            "hubId": 1,
            "name": "初期カート商品A",
            "nameToSlip": "初期カート商品A",
            "productType": "normal",
            "sku": "YP1SKU5",
            "fnsku": null,
            "janCode": null,
            "asin": null,
            "label": "YP1-5",
            "productLabelType": "product_id",
            "productUrl": "https://detail.1688.com/1",
            "productApiUrl": "https://detail.1688.com/1",
            "productImageUrl": null,
            "weight": 0,
            "height": 0,
            "width": 0,
            "depth": 0,
            "unitPrice": 230,
            "isDisabled": false,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "stockQuantity": 0,
            "productTypeLabel": "通常商品",
            "code": "YP1-5",
            "caseProductType": null,
            "caseChildrenProducts": [],
            "caseParentProducts": [],
            "productStocks": []
          },
          "processable": true,
          "otherPriceTotal": 0,
          "subTotal": 23000,
          "directDebitStatusLabel": "un_direct_debit",
          "depositTransactions": [],
          "orderDetailOthers": []
        },
        "isEditableStatus": true,
        "receiveStockCommissions": [],
        "leaveStocks": [],
        "customer": {
          "id": 1,
          "name": "KOU EI",
          "nameKana": null,
          "companyName": null,
          "email": "yiwu+customer@test.com",
          "emailVerifiedAt": "2024-06-25T04:37:29.000000Z",
          "emailVerifyLimitedAt": null,
          "emailVerifiedToken": null,
          "currentHubId": null,
          "amazonApiCode": null,
          "chatWorkId": null,
          "dedicatedAccountId": null,
          "countryId": null,
          "postalCode": null,
          "prefectureName": null,
          "cityName": null,
          "townName": null,
          "buildingName": null,
          "tel": null,
          "privateRemarks": null,
          "privateRemarksFilePath": null,
          "createdAt": "2024-06-25T04:37:29.000000Z",
          "updatedAt": "2024-06-25T04:37:29.000000Z",
          "deletedAt": null,
          "customerPlans": [
            {
              "id": 1,
              "customerId": 1,
              "planId": 1,
              "groupId": null,
              "status": "using",
              "isFree": "0",
              "employeeId": 1,
              "chatWorkId": null,
              "lastPaidAt": null,
              "createdAt": null,
              "updatedAt": null,
              "deletedAt": null,
              "plan": {
                "id": 1,
                "hubId": 1,
                "name": "義鳥 無料プラン",
                "imagePath": null,
                "planHeaderText": null,
                "paymentMethodCode": null,
                "trialPeriodLength": null,
                "trialPeriodUnit": null,
                "trialPrice": null,
                "paymentPeriodLength": null,
                "paymentPeriodUnit": null,
                "paymentPrice": null,
                "description1": null,
                "description2": null,
                "description3": null,
                "description4": null,
                "description5": null,
                "description6": null,
                "description7": null,
                "description8": null,
                "description9": null,
                "description10": null,
                "purchaseFee": null,
                "couponPeriodLength": null,
                "couponPeriodUnit": null,
                "couponEnableCount": null,
                "couponPercent": null,
                "applyButtonText": null,
                "applyButtonColorCode": null,
                "isDisabled": false,
                "isFree": 1,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              }
            }
          ]
        }
      },
      {
        "id": 2,
        "customerId": 1,
        "hubId": 1,
        "orderDetailId": 1,
        "trackingNo": "track_123",
        "status": "wait",
        "expectedArrivedOn": null,
        "receivedOn": null,
        "publicRemarks": "public_remarks_***",
        "publicRemarksFilePath": null,
        "privateRemarks": null,
        "privateRemarksFilePath": null,
        "isTransacted": false,
        "createdAt": "2024/06/25 13:37:29",
        "createdCustomerBy": 1,
        "createdEmployeeBy": null,
        "updatedAt": "2024/06/25 13:37:29",
        "deletedAt": null,
        "createdOn": "2024/06/25",
        "updatedOn": "2024/06/25",
        "uuid": "0991bdbe-6ec5-4947-b93e-b462d8b0f999",
        "code": "YP1-W2",
        "statusLabel": "入荷待ち",
        "receiveStockDetails": [
          {
            "id": 3,
            "receiveStockId": 2,
            "productId": 5,
            "requestedReceiveQuantity": 79,
            "inspectedQuantity": 0,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "uuid": "cee7812a-d81b-48c6-b33a-11b0b8aee367",
            "receiveQuantity": 0,
            "product": {
              "id": 5,
              "customerId": 1,
              "hubId": 1,
              "name": "初期カート商品A",
              "nameToSlip": null,
              "productType": "normal",
              "sku": "YP1SKU5",
              "fnsku": null,
              "janCode": null,
              "asin": null,
              "label": "YP1-5",
              "productLabelType": "product_id",
              "productUrl": "https://detail.1688.com/1",
              "productApiUrl": "https://detail.1688.com/1",
              "productImageUrl": null,
              "weight": 0,
              "height": 0,
              "width": 0,
              "depth": 0,
              "unitPrice": 230,
              "isDisabled": false,
              "createdAt": "2024/06/25 13:37:29",
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null
            },
            "receiveStock": {
              "id": 2,
              "customerId": 1,
              "hubId": 1,
              "orderDetailId": 1,
              "trackingNo": "track_123",
              "status": "wait",
              "expectedArrivedOn": null,
              "receivedOn": null,
              "publicRemarks": "public_remarks_***",
              "publicRemarksFilePath": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "isTransacted": false,
              "createdAt": "2024/06/25 13:37:29",
              "createdCustomerBy": 1,
              "createdEmployeeBy": null,
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null,
              "code": "YP1-W2"
            }
          },
          {
            "id": 4,
            "receiveStockId": 2,
            "productId": 3,
            "requestedReceiveQuantity": 90,
            "inspectedQuantity": 0,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "uuid": "44feefe0-9d16-40e4-95b9-b61c8a6f0e42",
            "receiveQuantity": 0,
            "product": {
              "id": 3,
              "customerId": 1,
              "hubId": 1,
              "name": "テスト商品D",
              "nameToSlip": null,
              "productType": "normal",
              "sku": "YP1SKU3",
              "fnsku": null,
              "janCode": "janABC",
              "asin": null,
              "label": "YP1-3",
              "productLabelType": "product_id",
              "productUrl": null,
              "productApiUrl": null,
              "productImageUrl": "https://link.storjshare.io/s/juxm7vvey6nkdmd2hi3fkj2seura/iiuu/p3.jpeg?wrap=0",
              "weight": 0,
              "height": 0,
              "width": 0,
              "depth": 0,
              "unitPrice": 1100,
              "isDisabled": false,
              "createdAt": "2024/06/25 13:37:29",
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null
            },
            "receiveStock": {
              "id": 2,
              "customerId": 1,
              "hubId": 1,
              "orderDetailId": 1,
              "trackingNo": "track_123",
              "status": "wait",
              "expectedArrivedOn": null,
              "receivedOn": null,
              "publicRemarks": "public_remarks_***",
              "publicRemarksFilePath": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "isTransacted": false,
              "createdAt": "2024/06/25 13:37:29",
              "createdCustomerBy": 1,
              "createdEmployeeBy": null,
              "updatedAt": "2024/06/25 13:37:29",
              "deletedAt": null,
              "code": "YP1-W2"
            }
          }
        ],
        "orderDetail": {
          "id": 1,
          "orderId": 1,
          "productId": 5,
          "mallProductId": null,
          "trackingNo": null,
          "productName": "初期カート商品A",
          "variation": "白",
          "quantity": 100,
          "orderStatus": "un_processed",
          "directDebitStatus": "un_direct_debit",
          "mall": "alibaba",
          "mallOrderId": null,
          "shopName": "ショップ名A",
          "unitPrice": 230,
          "postage": 0,
          "publicRemarks": null,
          "publicRemarksFilePath": null,
          "privateRemarks": null,
          "privateRemarksFilePath": null,
          "receipt": null,
          "receiptFilePath": null,
          "integratedId": null,
          "createdAt": "2024/06/25 13:37:29",
          "createdCustomerBy": 1,
          "createdEmployeeBy": null,
          "updatedAt": "2024/06/25 13:37:29",
          "deletedAt": null,
          "createdOn": "2024/06/25",
          "updatedOn": "2024/06/25",
          "uuid": "28826251-d3ac-4b02-bbf5-34d473f59881",
          "order": {
            "id": 1,
            "customerId": 1,
            "hubId": 1,
            "orderType": "oem",
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "customer": {
              "id": 1,
              "name": "KOU EI",
              "nameKana": null,
              "companyName": null,
              "email": "yiwu+customer@test.com",
              "emailVerifiedAt": "2024-06-25T04:37:29.000000Z",
              "emailVerifyLimitedAt": null,
              "emailVerifiedToken": null,
              "currentHubId": null,
              "amazonApiCode": null,
              "chatWorkId": null,
              "dedicatedAccountId": null,
              "countryId": null,
              "postalCode": null,
              "prefectureName": null,
              "cityName": null,
              "townName": null,
              "buildingName": null,
              "tel": null,
              "privateRemarks": null,
              "privateRemarksFilePath": null,
              "createdAt": "2024-06-25T04:37:29.000000Z",
              "updatedAt": "2024-06-25T04:37:29.000000Z",
              "deletedAt": null,
              "createdOn": "2024/06/25",
              "updatedOn": "2024/06/25",
              "code": "YP1",
              "plans": [
                {
                  "id": 1,
                  "hubId": 1,
                  "name": "義鳥 無料プラン",
                  "imagePath": null,
                  "planHeaderText": null,
                  "paymentMethodCode": null,
                  "trialPeriodLength": null,
                  "trialPeriodUnit": null,
                  "trialPrice": null,
                  "paymentPeriodLength": null,
                  "paymentPeriodUnit": null,
                  "paymentPrice": null,
                  "description1": null,
                  "description2": null,
                  "description3": null,
                  "description4": null,
                  "description5": null,
                  "description6": null,
                  "description7": null,
                  "description8": null,
                  "description9": null,
                  "description10": null,
                  "purchaseFee": null,
                  "couponPeriodLength": null,
                  "couponPeriodUnit": null,
                  "couponEnableCount": null,
                  "couponPercent": null,
                  "applyButtonText": null,
                  "applyButtonColorCode": null,
                  "isDisabled": false,
                  "isFree": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null,
                  "pivot": {
                    "customer_id": 1,
                    "plan_id": 1,
                    "status": "using"
                  },
                  "hub": {
                    "id": 1,
                    "name": "義鳥",
                    "iconPath": null,
                    "code": "yiwu",
                    "countryId": 1,
                    "currencyId": 1,
                    "forContact": false,
                    "isDomestic": 1,
                    "companyName": null,
                    "postalCode": null,
                    "prefectureName": null,
                    "cityName": null,
                    "townName": null,
                    "buildingName": null,
                    "invoiceNo": null,
                    "description": null,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null
                  }
                }
              ],
              "currentCustomerPlan": null,
              "customerPlans": [
                {
                  "id": 1,
                  "customerId": 1,
                  "planId": 1,
                  "groupId": null,
                  "status": "using",
                  "isFree": "0",
                  "employeeId": 1,
                  "chatWorkId": null,
                  "lastPaidAt": null,
                  "createdAt": null,
                  "updatedAt": null,
                  "deletedAt": null,
                  "statusLabel": "利用中",
                  "hub": {
                    "id": 1,
                    "name": "義鳥",
                    "iconPath": null,
                    "code": "yiwu",
                    "countryId": 1,
                    "currencyId": 1,
                    "forContact": false,
                    "isDomestic": 1,
                    "companyName": null,
                    "postalCode": null,
                    "prefectureName": null,
                    "cityName": null,
                    "townName": null,
                    "buildingName": null,
                    "invoiceNo": null,
                    "description": null,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null
                  },
                  "plan": {
                    "id": 1,
                    "hubId": 1,
                    "name": "義鳥 無料プラン",
                    "imagePath": null,
                    "planHeaderText": null,
                    "paymentMethodCode": null,
                    "trialPeriodLength": null,
                    "trialPeriodUnit": null,
                    "trialPrice": null,
                    "paymentPeriodLength": null,
                    "paymentPeriodUnit": null,
                    "paymentPrice": null,
                    "description1": null,
                    "description2": null,
                    "description3": null,
                    "description4": null,
                    "description5": null,
                    "description6": null,
                    "description7": null,
                    "description8": null,
                    "description9": null,
                    "description10": null,
                    "purchaseFee": null,
                    "couponPeriodLength": null,
                    "couponPeriodUnit": null,
                    "couponEnableCount": null,
                    "couponPercent": null,
                    "applyButtonText": null,
                    "applyButtonColorCode": null,
                    "isDisabled": false,
                    "isFree": 1,
                    "createdAt": "2024/06/25 13:37:28",
                    "updatedAt": "2024/06/25 13:37:28",
                    "deletedAt": null,
                    "hub": {
                      "id": 1,
                      "name": "義鳥",
                      "iconPath": null,
                      "code": "yiwu",
                      "countryId": 1,
                      "currencyId": 1,
                      "forContact": false,
                      "isDomestic": 1,
                      "companyName": null,
                      "postalCode": null,
                      "prefectureName": null,
                      "cityName": null,
                      "townName": null,
                      "buildingName": null,
                      "invoiceNo": null,
                      "description": null,
                      "createdAt": "2024/06/25 13:37:28",
                      "updatedAt": "2024/06/25 13:37:28",
                      "deletedAt": null
                    }
                  }
                }
              ]
            },
            "code": "YP1-O1",
            "postageTotal": 0,
            "otherPriceTotal": 0,
            "total": 280000,
            "detailCount": 3,
            "hub": {
              "id": 1,
              "name": "義鳥",
              "iconPath": null,
              "code": "yiwu",
              "countryId": 1,
              "currencyId": 1,
              "forContact": false,
              "isDomestic": 1,
              "companyName": null,
              "postalCode": null,
              "prefectureName": null,
              "cityName": null,
              "townName": null,
              "buildingName": null,
              "invoiceNo": null,
              "description": null,
              "createdAt": "2024/06/25 13:37:28",
              "updatedAt": "2024/06/25 13:37:28",
              "deletedAt": null,
              "createdOn": "2024/06/25",
              "updatedOn": "2024/06/25",
              "groups": [
                {
                  "id": 1,
                  "name": "A班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 2,
                  "name": "B班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 3,
                  "name": "C班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 4,
                  "name": "D班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                },
                {
                  "id": 5,
                  "name": "E班",
                  "hubId": 1,
                  "createdAt": "2024/06/25 13:37:28",
                  "updatedAt": "2024/06/25 13:37:28",
                  "deletedAt": null
                }
              ],
              "country": {
                "id": 1,
                "code": "86",
                "name": "中国",
                "isJapan": false,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              },
              "currency": {
                "id": 1,
                "name": "CNY",
                "nameToJp": "元",
                "decimalPlaces": 2,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              },
              "currentTaxRate": {
                "id": 1,
                "hubId": 1,
                "name": "消費税",
                "startedOn": "2024-06-26",
                "rate": 0,
                "createdAt": "2024/06/26 11:33:21",
                "updatedAt": "2024/06/26 11:33:21"
              },
              "currentCustomerPlan": {
                "id": 1,
                "hubId": 1,
                "name": "義鳥 無料プラン",
                "imagePath": null,
                "planHeaderText": null,
                "paymentMethodCode": null,
                "trialPeriodLength": null,
                "trialPeriodUnit": null,
                "trialPrice": null,
                "paymentPeriodLength": null,
                "paymentPeriodUnit": null,
                "paymentPrice": null,
                "description1": null,
                "description2": null,
                "description3": null,
                "description4": null,
                "description5": null,
                "description6": null,
                "description7": null,
                "description8": null,
                "description9": null,
                "description10": null,
                "purchaseFee": null,
                "couponPeriodLength": null,
                "couponPeriodUnit": null,
                "couponEnableCount": null,
                "couponPercent": null,
                "applyButtonText": null,
                "applyButtonColorCode": null,
                "isDisabled": false,
                "isFree": 1,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null,
                "customerPlans": [
                  {
                    "id": 1,
                    "customerId": 1,
                    "planId": 1,
                    "groupId": null,
                    "status": "using",
                    "isFree": "0",
                    "employeeId": 1,
                    "chatWorkId": null,
                    "lastPaidAt": null,
                    "createdAt": null,
                    "updatedAt": null,
                    "deletedAt": null
                  }
                ]
              }
            },
            "orderDetails": [
              {
                "id": 1,
                "orderId": 1,
                "productId": 5,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品A",
                "variation": "白",
                "quantity": 100,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": "alibaba",
                "mallOrderId": null,
                "shopName": "ショップ名A",
                "unitPrice": 230,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              },
              {
                "id": 2,
                "orderId": 1,
                "productId": 1,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品B",
                "variation": "黒",
                "quantity": 20,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": "alibaba",
                "mallOrderId": null,
                "shopName": "ショップ名A",
                "unitPrice": 350,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              },
              {
                "id": 3,
                "orderId": 1,
                "productId": 6,
                "mallProductId": null,
                "trackingNo": null,
                "productName": "初期カート商品C",
                "variation": "赤",
                "quantity": 500,
                "orderStatus": "un_processed",
                "directDebitStatus": "un_direct_debit",
                "mall": null,
                "mallOrderId": null,
                "shopName": "ショップ名B",
                "unitPrice": 500,
                "postage": 0,
                "publicRemarks": null,
                "publicRemarksFilePath": null,
                "privateRemarks": null,
                "privateRemarksFilePath": null,
                "receipt": null,
                "receiptFilePath": null,
                "integratedId": null,
                "createdAt": "2024/06/25 13:37:29",
                "createdCustomerBy": 1,
                "createdEmployeeBy": null,
                "updatedAt": "2024/06/25 13:37:29",
                "deletedAt": null,
                "orderDetailOthers": []
              }
            ]
          },
          "orderStatusLabel": "未処理",
          "product": {
            "id": 5,
            "customerId": 1,
            "hubId": 1,
            "name": "初期カート商品A",
            "nameToSlip": "初期カート商品A",
            "productType": "normal",
            "sku": "YP1SKU5",
            "fnsku": null,
            "janCode": null,
            "asin": null,
            "label": "YP1-5",
            "productLabelType": "product_id",
            "productUrl": "https://detail.1688.com/1",
            "productApiUrl": "https://detail.1688.com/1",
            "productImageUrl": null,
            "weight": 0,
            "height": 0,
            "width": 0,
            "depth": 0,
            "unitPrice": 230,
            "isDisabled": false,
            "createdAt": "2024/06/25 13:37:29",
            "updatedAt": "2024/06/25 13:37:29",
            "deletedAt": null,
            "createdOn": "2024/06/25",
            "updatedOn": "2024/06/25",
            "stockQuantity": 0,
            "productTypeLabel": "通常商品",
            "code": "YP1-5",
            "caseProductType": null,
            "caseChildrenProducts": [],
            "caseParentProducts": [],
            "productStocks": []
          },
          "processable": true,
          "otherPriceTotal": 0,
          "subTotal": 23000,
          "directDebitStatusLabel": "un_direct_debit",
          "depositTransactions": [],
          "orderDetailOthers": []
        },
        "isEditableStatus": true,
        "receiveStockCommissions": [],
        "leaveStocks": [],
        "customer": {
          "id": 1,
          "name": "KOU EI",
          "nameKana": null,
          "companyName": null,
          "email": "yiwu+customer@test.com",
          "emailVerifiedAt": "2024-06-25T04:37:29.000000Z",
          "emailVerifyLimitedAt": null,
          "emailVerifiedToken": null,
          "currentHubId": null,
          "amazonApiCode": null,
          "chatWorkId": null,
          "dedicatedAccountId": null,
          "countryId": null,
          "postalCode": null,
          "prefectureName": null,
          "cityName": null,
          "townName": null,
          "buildingName": null,
          "tel": null,
          "privateRemarks": null,
          "privateRemarksFilePath": null,
          "createdAt": "2024-06-25T04:37:29.000000Z",
          "updatedAt": "2024-06-25T04:37:29.000000Z",
          "deletedAt": null,
          "customerPlans": [
            {
              "id": 1,
              "customerId": 1,
              "planId": 1,
              "groupId": null,
              "status": "using",
              "isFree": "0",
              "employeeId": 1,
              "chatWorkId": null,
              "lastPaidAt": null,
              "createdAt": null,
              "updatedAt": null,
              "deletedAt": null,
              "plan": {
                "id": 1,
                "hubId": 1,
                "name": "義鳥 無料プラン",
                "imagePath": null,
                "planHeaderText": null,
                "paymentMethodCode": null,
                "trialPeriodLength": null,
                "trialPeriodUnit": null,
                "trialPrice": null,
                "paymentPeriodLength": null,
                "paymentPeriodUnit": null,
                "paymentPrice": null,
                "description1": null,
                "description2": null,
                "description3": null,
                "description4": null,
                "description5": null,
                "description6": null,
                "description7": null,
                "description8": null,
                "description9": null,
                "description10": null,
                "purchaseFee": null,
                "couponPeriodLength": null,
                "couponPeriodUnit": null,
                "couponEnableCount": null,
                "couponPercent": null,
                "applyButtonText": null,
                "applyButtonColorCode": null,
                "isDisabled": false,
                "isFree": 1,
                "createdAt": "2024/06/25 13:37:28",
                "updatedAt": "2024/06/25 13:37:28",
                "deletedAt": null
              }
            }
          ]
        }
      }
    ]
  }
}